name: syncmatica
version: '${project.version}'
main: com.github.bunnyi.syncmatica.SyncmaticaPlugin
api-version: '1.20'

commands:
  test:
    description: This is a demo command.
    usage: /<command> [player]
    permission-message: You don't have <permission>